from __future__ import annotations

# Global port network (30 ports across 5 regions)
# Coordinates are approximate and only used for distance estimation.

PORTS = [
    # West Coast India
    {
        "id": "mundra",
        "name": "Mundra Port, Gujarat, India",
        "lat": 22.839,
        "lng": 69.721,
        "coast": "west",
        "region": "india",
        "infrastructure_quality": 0.85,
        "customs_hours": 8.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.45,
        "base_security_risk": 0.18,
    },
    {
        "id": "kandla",
        "name": "Deendayal Port (Kandla), Gujarat, India",
        "lat": 23.033,
        "lng": 70.217,
        "coast": "west",
        "region": "india",
        "infrastructure_quality": 0.80,
        "customs_hours": 9.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.40,
        "base_security_risk": 0.16,
    },
    {
        "id": "jnpt",
        "name": "Jawaharlal Nehru Port (JNPT), Navi Mumbai, India",
        "lat": 18.950,
        "lng": 72.950,
        "coast": "west",
        "region": "india",
        "infrastructure_quality": 0.85,
        "customs_hours": 8.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.55,
        "base_security_risk": 0.20,
    },
    {
        "id": "mumbai",
        "name": "Mumbai Port, Maharashtra, India",
        "lat": 18.944,
        "lng": 72.839,
        "coast": "west",
        "region": "india",
        "infrastructure_quality": 0.80,
        "customs_hours": 9.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.55,
        "base_security_risk": 0.22,
    },
    {
        "id": "mormugao",
        "name": "Mormugao Port, Goa, India",
        "lat": 15.405,
        "lng": 73.799,
        "coast": "west",
        "region": "india",
        "infrastructure_quality": 0.75,
        "customs_hours": 10.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.30,
        "base_security_risk": 0.18,
    },
    {
        "id": "new_mangalore",
        "name": "New Mangalore Port, Karnataka, India",
        "lat": 12.914,
        "lng": 74.807,
        "coast": "west",
        "region": "india",
        "infrastructure_quality": 0.78,
        "customs_hours": 9.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.35,
        "base_security_risk": 0.17,
    },
    {
        "id": "kochi",
        "name": "Cochin Port (Kochi), Kerala, India",
        "lat": 9.967,
        "lng": 76.270,
        "coast": "west",
        "region": "india",
        "infrastructure_quality": 0.80,
        "customs_hours": 8.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.38,
        "base_security_risk": 0.16,
    },
    # East Coast India
    {
        "id": "tuticorin",
        "name": "V.O. Chidambaranar Port (Thoothukudi), Tamil Nadu, India",
        "lat": 8.764,
        "lng": 78.180,
        "coast": "east",
        "region": "india",
        "infrastructure_quality": 0.78,
        "customs_hours": 9.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.33,
        "base_security_risk": 0.17,
    },
    {
        "id": "chennai",
        "name": "Chennai Port, Tamil Nadu, India",
        "lat": 13.095,
        "lng": 80.292,
        "coast": "east",
        "region": "india",
        "infrastructure_quality": 0.82,
        "customs_hours": 8.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.48,
        "base_security_risk": 0.18,
    },
    {
        "id": "kamarajar",
        "name": "Kamarajar Port (Ennore), Tamil Nadu, India",
        "lat": 13.235,
        "lng": 80.333,
        "coast": "east",
        "region": "india",
        "infrastructure_quality": 0.80,
        "customs_hours": 8.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.42,
        "base_security_risk": 0.17,
    },
    {
        "id": "vizag",
        "name": "Visakhapatnam Port, Andhra Pradesh, India",
        "lat": 17.689,
        "lng": 83.281,
        "coast": "east",
        "region": "india",
        "infrastructure_quality": 0.82,
        "customs_hours": 8.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.46,
        "base_security_risk": 0.18,
    },
    {
        "id": "paradip",
        "name": "Paradip Port, Odisha, India",
        "lat": 20.265,
        "lng": 86.691,
        "coast": "east",
        "region": "india",
        "infrastructure_quality": 0.80,
        "customs_hours": 9.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.44,
        "base_security_risk": 0.18,
    },
    {
        "id": "kolkata_haldia",
        "name": "Kolkata Port (Haldia Dock Complex), West Bengal, India",
        "lat": 22.021,
        "lng": 88.059,
        "coast": "east",
        "region": "india",
        "infrastructure_quality": 0.75,
        "customs_hours": 10.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.50,
        "base_security_risk": 0.19,
    },
    # Middle East
    {
        "id": "jebel_ali",
        "name": "Jebel Ali Port (Dubai), UAE",
        "lat": 25.013,
        "lng": 55.061,
        "coast": "international",
        "region": "middle_east",
        "infrastructure_quality": 0.95,
        "customs_hours": 6.0,
        "piracy_risk": 0.05,
        "base_congestion": 0.35,
        "base_security_risk": 0.15,
    },
    {
        "id": "jeddah",
        "name": "Jeddah Islamic Port, Saudi Arabia",
        "lat": 21.486,
        "lng": 39.188,
        "coast": "international",
        "region": "middle_east",
        "infrastructure_quality": 0.85,
        "customs_hours": 8.0,
        "piracy_risk": 0.15,
        "base_congestion": 0.40,
        "base_security_risk": 0.22,
    },
    {
        "id": "bandar_abbas",
        "name": "Bandar Abbas Port, Iran",
        "lat": 27.140,
        "lng": 56.200,
        "coast": "international",
        "region": "middle_east",
        "infrastructure_quality": 0.70,
        "customs_hours": 12.0,
        "piracy_risk": 0.10,
        "base_congestion": 0.50,
        "base_security_risk": 0.30,
    },
    {
        "id": "salalah",
        "name": "Port of Salalah, Oman",
        "lat": 16.950,
        "lng": 54.010,
        "coast": "international",
        "region": "middle_east",
        "infrastructure_quality": 0.88,
        "customs_hours": 6.0,
        "piracy_risk": 0.12,
        "base_congestion": 0.30,
        "base_security_risk": 0.18,
    },
    {
        "id": "port_said",
        "name": "Port Said (Suez Canal), Egypt",
        "lat": 31.260,
        "lng": 32.310,
        "coast": "international",
        "region": "middle_east",
        "infrastructure_quality": 0.82,
        "customs_hours": 10.0,
        "piracy_risk": 0.08,
        "base_congestion": 0.45,
        "base_security_risk": 0.20,
    },
    # Southeast Asia
    {
        "id": "singapore",
        "name": "Port of Singapore, Singapore",
        "lat": 1.264,
        "lng": 103.840,
        "coast": "international",
        "region": "southeast_asia",
        "infrastructure_quality": 0.98,
        "customs_hours": 4.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.45,
        "base_security_risk": 0.10,
    },
    {
        "id": "klang",
        "name": "Port Klang, Malaysia",
        "lat": 3.000,
        "lng": 101.350,
        "coast": "international",
        "region": "southeast_asia",
        "infrastructure_quality": 0.88,
        "customs_hours": 6.0,
        "piracy_risk": 0.03,
        "base_congestion": 0.40,
        "base_security_risk": 0.14,
    },
    {
        "id": "laem_chabang",
        "name": "Laem Chabang Port, Thailand",
        "lat": 13.080,
        "lng": 100.890,
        "coast": "international",
        "region": "southeast_asia",
        "infrastructure_quality": 0.85,
        "customs_hours": 7.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.38,
        "base_security_risk": 0.15,
    },
    {
        "id": "cat_lai",
        "name": "Cat Lai Port (Ho Chi Minh City), Vietnam",
        "lat": 10.760,
        "lng": 106.790,
        "coast": "international",
        "region": "southeast_asia",
        "infrastructure_quality": 0.80,
        "customs_hours": 8.0,
        "piracy_risk": 0.03,
        "base_congestion": 0.42,
        "base_security_risk": 0.16,
    },
    # East Asia
    {
        "id": "shanghai",
        "name": "Port of Shanghai, China",
        "lat": 31.220,
        "lng": 121.480,
        "coast": "international",
        "region": "east_asia",
        "infrastructure_quality": 0.95,
        "customs_hours": 5.0,
        "piracy_risk": 0.01,
        "base_congestion": 0.50,
        "base_security_risk": 0.12,
    },
    {
        "id": "hong_kong",
        "name": "Port of Hong Kong, Hong Kong",
        "lat": 22.300,
        "lng": 114.160,
        "coast": "international",
        "region": "east_asia",
        "infrastructure_quality": 0.93,
        "customs_hours": 4.0,
        "piracy_risk": 0.01,
        "base_congestion": 0.42,
        "base_security_risk": 0.12,
    },
    {
        "id": "singapore_east",
        "name": "Singapore Eastern Anchorage, Singapore",
        "lat": 1.275,
        "lng": 103.900,
        "coast": "international",
        "region": "east_asia",
        "infrastructure_quality": 0.98,
        "customs_hours": 4.0,
        "piracy_risk": 0.02,
        "base_congestion": 0.35,
        "base_security_risk": 0.10,
    },
    # Europe
    {
        "id": "rotterdam",
        "name": "Port of Rotterdam, Netherlands",
        "lat": 51.924,
        "lng": 4.477,
        "coast": "international",
        "region": "europe",
        "infrastructure_quality": 0.98,
        "customs_hours": 4.0,
        "piracy_risk": 0.00,
        "base_congestion": 0.40,
        "base_security_risk": 0.08,
    },
    {
        "id": "antwerp",
        "name": "Port of Antwerp, Belgium",
        "lat": 51.219,
        "lng": 4.402,
        "coast": "international",
        "region": "europe",
        "infrastructure_quality": 0.93,
        "customs_hours": 5.0,
        "piracy_risk": 0.00,
        "base_congestion": 0.38,
        "base_security_risk": 0.08,
    },
    {
        "id": "hamburg",
        "name": "Port of Hamburg, Germany",
        "lat": 53.551,
        "lng": 9.993,
        "coast": "international",
        "region": "europe",
        "infrastructure_quality": 0.91,
        "customs_hours": 5.0,
        "piracy_risk": 0.00,
        "base_congestion": 0.42,
        "base_security_risk": 0.09,
    },
]

# Adjacency list describing realistic coastal and international connectivity.
SEA_LANES = {
    # West Coast India chain
    "kandla": ["mundra", "jnpt"],
    "mundra": ["kandla", "jnpt", "jebel_ali"],
    "mumbai": ["jnpt", "mormugao"],
    "jnpt": ["mundra", "kandla", "mumbai", "mormugao", "jebel_ali"],
    "mormugao": ["jnpt", "mumbai", "new_mangalore"],
    "new_mangalore": ["mormugao", "kochi"],
    "kochi": ["new_mangalore", "tuticorin", "chennai", "singapore"],
    
    # East Coast India chain
    "tuticorin": ["kochi", "chennai"],
    "chennai": ["tuticorin", "kamarajar", "kochi", "vizag", "singapore"],
    "kamarajar": ["chennai", "vizag"],
    "vizag": ["kamarajar", "chennai", "paradip", "singapore"],
    "paradip": ["vizag", "kolkata_haldia"],
    "kolkata_haldia": ["paradip", "singapore"],
    
    # Middle East
    "jebel_ali": ["mundra", "jnpt", "bandar_abbas", "salalah"],
    "bandar_abbas": ["jebel_ali"],
    "salalah": ["jebel_ali", "jeddah"],
    "jeddah": ["salalah", "port_said"],
    "port_said": ["jeddah", "rotterdam", "antwerp", "hamburg"],
    
    # Southeast Asia
    "singapore": ["kochi", "chennai", "vizag", "kolkata_haldia", "klang", "laem_chabang", "singapore_east"],
    "klang": ["singapore"],
    "laem_chabang": ["singapore", "cat_lai"],
    "cat_lai": ["laem_chabang", "hong_kong", "shanghai"],
    
    # East Asia
    "singapore_east": ["singapore", "hong_kong", "shanghai"],
    "hong_kong": ["cat_lai", "singapore_east", "shanghai"],
    "shanghai": ["cat_lai", "singapore_east", "hong_kong"],
    
    # Europe
    "rotterdam": ["port_said", "antwerp", "hamburg"],
    "antwerp": ["rotterdam", "port_said"],
    "hamburg": ["rotterdam", "port_said"],
}


# --- Heuristic constants (units: hours, INR, nautical miles) ---

# Sea travel
VESSEL_SPEED_KNOTS = 16.0  # nm/hour
PORT_HANDLING_HOURS = 6.0  # load/unload at each port call
TRANSSHIPMENT_EXTRA_HOURS = 10.0  # additional handling at intermediate port

# Road legs (city->port / port->city)
TRUCK_SPEED_KMPH = 45.0

# Cost model
SEA_COST_BASE_PER_KG_INR = 1.2
SEA_COST_PER_KG_PER_NM_INR = 0.015
PORT_FEE_BASE_INR = 800.0
TRANSSHIPMENT_FEE_INR = 1200.0
ROAD_COST_PER_KM_PER_TON_INR = 10.0
ROAD_HANDLING_BASE_INR = 300.0

# Risk weights (combined and clamped into 0..1)
RISK_WEIGHTS = {
    "weather": 0.30,
    "congestion": 0.30,
    "security": 0.25,
    "transshipment": 0.15,
}
