import { LegalPage } from '@/components/legal/LegalPage';
import { buildPageMetadata } from '@/lib/seo';

export const metadata = buildPageMetadata({
  title: 'Terms & Conditions',
  description: 'Terms and conditions for using the LogiFlow multimodal freight planning platform.',
  path: '/terms',
});

const sections = [
  {
    heading: '1. Acceptance of Terms',
    content: (
      <p>
        By accessing or using LogiFlow, you agree to be bound by these Terms and Conditions.
        LogiFlow is an academic and research project built for the Google Solution Challenge 2026.
        If you do not agree with any part of these terms, please do not use the platform.
      </p>
    ),
  },
  {
    heading: '2. Use of Platform',
    content: (
      <>
        <p>
          LogiFlow provides multimodal freight route planning, comparison, and optimisation tools.
          You may use the platform for personal, educational, or research purposes.
        </p>
        <p>
          You agree not to misuse the platform, attempt to access systems or data without
          authorisation, or use the service in any way that could harm its availability for
          other users.
        </p>
      </>
    ),
  },
  {
    heading: '3. Shipment Planning Disclaimer',
    content: (
      <p>
        Route suggestions, transit times, cost estimates, and multimodal recommendations
        generated by LogiFlow are for informational and planning purposes only. They are
        derived from third-party data sources and algorithmic models that may be incomplete
        or out of date. Do not rely on LogiFlow output for commercial shipping decisions
        without independent verification.
      </p>
    ),
  },
  {
    heading: '4. Data Accuracy Disclaimer',
    content: (
      <p>
        LogiFlow integrates data from providers including TomTom, OpenWeatherMap, Indian
        Railways, and others. We do not guarantee the accuracy, completeness, or timeliness
        of any data displayed. Live train positions, weather conditions, and route geometries
        are sourced from third parties and may not reflect actual real-world conditions.
      </p>
    ),
  },
  {
    heading: '5. Limitation of Liability',
    content: (
      <p>
        LogiFlow is provided &quot;as is&quot; without warranty of any kind. To the fullest extent
        permitted by applicable law, the LogiFlow team shall not be liable for any direct,
        indirect, incidental, or consequential damages arising from your use of or inability
        to use the platform, including any reliance on route or logistics data provided.
      </p>
    ),
  },
  {
    heading: '6. Account Responsibilities',
    content: (
      <>
        <p>
          Access to shipment planning features requires signing in with a Google account.
          You are responsible for all activity associated with your account.
        </p>
        <p>
          Do not share your session with others. If you believe your account has been
          compromised, sign out immediately and review your Google account security settings.
        </p>
      </>
    ),
  },
  {
    heading: '7. Service Availability',
    content: (
      <p>
        LogiFlow is hosted on cloud infrastructure and may experience downtime for maintenance
        or due to factors outside our control. We do not guarantee uninterrupted availability.
        As an academic project, the service may be modified, suspended, or discontinued at
        any time.
      </p>
    ),
  },
  {
    heading: '8. Contact Information',
    content: (
      <p>
        LogiFlow is an open-source project submitted to the Google Solution Challenge 2026.
        For queries, feedback, or concerns, please open an issue on the project&apos;s GitHub
        repository or contact the development team through the repository&apos;s listed contact
        channels.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      subtitle="Please read these terms carefully before using LogiFlow."
      lastUpdated="June 2026"
      sections={sections}
    />
  );
}
